#!/bin/bash
if [ -f .current_level ]
then
  current_level=$(<.current_level)
else
  current_level=0
fi
next_level=$[current_level+1]
echo $next_level > "./.current_level"
echo "Moving savepoint " $next_level
#ln -s ../save-points/$next_level ./workshop-app/